# Spawn a Server
- import_tasks: "{{ role_path }}/tasks/spawn_do_droplet.yml"
  tags: always

# Spawn a 'Space'
- import_tasks: "{{ role_path }}/tasks/spawn_do_space.yml"
  tags: digitalocean-space

# Save server IPs
- import_tasks: "{{ role_path }}/tasks/save_server_ips.yml"
  tags: always

# Add the new host to AWX
- import_tasks: "{{ role_path }}/tasks/add_hosts.yml"
  tags: always

# Connects an existing BYO server
- import_tasks: "{{ role_path }}/tasks/connect_byo_server.yml"
  tags: always

# Create initial variable files
- import_tasks: "{{ role_path }}/tasks/generate_initial_variables.yml"
  tags: always
